### ISSUE TITLE
has_many :through ability (1.6.5)

### ISSUE THREAD

**Issue by codezomb** [ryanb/cancan#474]
I did some testing with cancan today, and one thing I noticed, is that with my has_many :through ability, I'm unable to reference the parent. The idea is that, a user is only tied to a project through a participation. This includes the owner of the project. I can create the participation just fine when the project is created, however, I'm unable to add further participations to the project.

If I try a block, I end up with a participation object, but no project.

```
RuntimeError (--- !ruby/object:Participation
attributes:
  user_id: 
  project_id: 
  role: 
  created_at: 
  updated_at: 
attributes_cache: {}
new_record: true
readonly: false
destroyed: false
marked_for_destruction: false
previously_changed: {}
changed_attributes: {}
name: Mike Kelley
email: mkelle1@gmail.com
custom_contexts: []
participation_type_list:
- Project Investor
):
```

ability.rb

```
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can    :create,  Project unless user.new_record?
    can    :read,    Project, :participations => { :user => user, :role => %w[owner admin user] }
    can    :manage,  Project, :participations => { :user => user, :role => %w[owner admin] }
    cannot :delete,  Project, :participations => { :user => user, :role => %w[admin user] }

    can    :manage,  Participation, :project => { :participations => { :user => user, :role => %w[owner admin] } }
  end
end
```

My Form:

```
<%= form_for [@project, Participations.new], :remote => true do |f| %>
  <%= f.text_field :name, :placeholder => "Name" %>
  <%= f.email_field :email, :placeholder => "Email" %>
  <%= f.select :participation_type_list, options_for_select(Participation::TYPES.split(",")) %>
  <%= f.submit "Add", :class => "button gray small css3" %>
<% end %>
```

This produces the proper action:

```
<form id="new_participation_form" class="new_participation" method="post" data-remote="true" action="/projects/126/participations" accept-charset="UTF-8">
```

My Controller:

```
class ParticipationsController < InheritedResources::Base

  load_and_authorize_resource :project
  load_and_authorize_resource :participation, :through => :project

  def create
    user = User.find_by_email(params[:participation][:email])
    user ||= invite_user

    @participation.user   = user
    @participation.actor  = current_user

    create! do |success, failure|
      success.json { render :json => @participation.to_json }
    end
  end

end
```
